#!/usr/bin/env bash
set -x

source /common.sh
install_chroot_fail_on_error_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/root /
unpack /filesystem/boot /boot

apt-get -y --force-yes install fbi atop unclutter matchbox openvpn --fix-missing
sudo pip install ino pyyaml


pushd /home/pi

  # install system wide numpy and scipy and copy to venv to save time
  apt-get -y --force-yes install python-scipy python-numpy --fix-missing
  cp -v -r --preserve=mode,timestamps /usr/lib/python2.7/dist-packages/scipy* /home/pi/oprint/lib/python2.7/site-packages
  cp -v -r --preserve=mode,timestamps /usr/lib/python2.7/dist-packages/numpy* /home/pi/oprint/lib/python2.7/site-packages
  apt-get -y remove python-scipy python-numpy

  # install chromium
  wget https://s3-us-west-2.amazonaws.com/v8-file-transfer/chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.15.04.1.1181_armhf.deb
  wget https://s3-us-west-2.amazonaws.com/v8-file-transfer/chromium-browser-l10n_45.0.2454.85-0ubuntu0.15.04.1.1181_all.deb
  wget https://s3-us-west-2.amazonaws.com/v8-file-transfer/chromium-browser_45.0.2454.85-0ubuntu0.15.04.1.1181_armhf.deb
  dpkg -i chromium-codecs-ffmpeg-extra_45.0.2454.85-0ubuntu0.15.04.1.1181_armhf.deb
  dpkg -i chromium-browser-l10n_45.0.2454.85-0ubuntu0.15.04.1.1181_all.deb chromium-browser_45.0.2454.85-0ubuntu0.15.04.1.1181_armhf.deb
  rm chromium-*

  # install wifi drivers
  wget https://s3-us-west-2.amazonaws.com/v8-file-transfer/8812au-4.1.17-v7-834.tar.gz
  tar xzf 8812au-4.1.17-v7-834.tar.gz
  ./install.sh

  # install webmin
  #apt-get -y --force-yes install perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python --fix-missing
  #wget http://prdownloads.sourceforge.net/webadmin/webmin_1.791_all.deb
  #dpkg --install webmin_1.791_all.deb
  #rm webmin_1.791_all.deb
  #update-rc.d -f webmin remove

  # install 3rd party octoprint plugins
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-RequestSpinner/archive/master.zip
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-Yamlpatcher/archive/master.zip
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/octoprint-customControl/archive/master.zip
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-SystemCommandEditor/archive/master.zip
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-ScreenSquish/archive/master.zip
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-ActiveFilters/archive/master.zip

  # install custom octoprint plugins
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-Automation-Scripts/archive/master.zip
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-FirmwareUpdate/archive/master.zip
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-V8theme/archive/master.zip
  sudo -u pi /home/pi/oprint/bin/pip install https://github.com/Voxel8/OctoPrint-Schedule-Reboot/archive/master.zip

  #Custom Splash screen setup
  sudo install -Dm755 startup/asplashscreen /etc/init.d/asplashscreen
  sudo insserv /etc/init.d/asplashscreen
  sudo install -Dm644 startup/splash.tiff /etc/splash.tiff

  #Start browser without desktop and cursor
  sudo install -Dm755 startup/directly_to_browser.sh /etc/directly_to_browser.sh

  #stop directly booting to default Desktop
  systemctl_if_exists set-default multi-user.target

popd

#cleanup
apt-get clean
apt-get autoremove -y
